[2024-12-15T04:21:37.584+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T04:21:37.596+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data scheduled__2024-12-14T04:00:00+00:00 [queued]>
[2024-12-15T04:21:37.601+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_etl.collect_data scheduled__2024-12-14T04:00:00+00:00 [queued]>
[2024-12-15T04:21:37.601+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-15T04:21:37.608+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_data> on 2024-12-14 04:00:00+00:00
[2024-12-15T04:21:37.612+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1636) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-15T04:21:37.613+0000] {standard_task_runner.py:72} INFO - Started process 1637 to run task
[2024-12-15T04:21:37.613+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_etl', 'collect_data', 'scheduled__2024-12-14T04:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_auto.py', '--cfg-path', '/tmp/tmpcfjdctsd']
[2024-12-15T04:21:37.615+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask collect_data
[2024-12-15T04:21:37.647+0000] {task_command.py:467} INFO - Running <TaskInstance: data_pipeline_etl.collect_data scheduled__2024-12-14T04:00:00+00:00 [running]> on host bea0c6fb71a7
[2024-12-15T04:21:37.716+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_etl' AIRFLOW_CTX_TASK_ID='collect_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-14T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-14T04:00:00+00:00'
[2024-12-15T04:21:37.717+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T04:21:37.734+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-15T04:21:37.735+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/data-pipeline-project/product_data_scraper.py']
[2024-12-15T04:21:37.742+0000] {subprocess.py:99} INFO - Output:
[2024-12-15T04:25:43.173+0000] {job.py:229} INFO - Heartbeat recovered after 220.39 seconds
[2024-12-15T04:34:24.576+0000] {subprocess.py:106} INFO - 320번 데이터 수집 시작
[2024-12-15T04:34:24.580+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.581+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.581+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.581+0000] {subprocess.py:106} INFO - #0 0xaaaabef17d44 <unknown>
[2024-12-15T04:34:24.582+0000] {subprocess.py:106} INFO - #1 0xaaaabec3e374 <unknown>
[2024-12-15T04:34:24.582+0000] {subprocess.py:106} INFO - #2 0xaaaabec4afe0 <unknown>
[2024-12-15T04:34:24.582+0000] {subprocess.py:106} INFO - #3 0xaaaabec43318 <unknown>
[2024-12-15T04:34:24.582+0000] {subprocess.py:106} INFO - #4 0xaaaabec427ac <unknown>
[2024-12-15T04:34:24.583+0000] {subprocess.py:106} INFO - #5 0xaaaabec444b8 <unknown>
[2024-12-15T04:34:24.583+0000] {subprocess.py:106} INFO - #6 0xaaaabec4457c <unknown>
[2024-12-15T04:34:24.583+0000] {subprocess.py:106} INFO - #7 0xaaaabec7b0c8 <unknown>
[2024-12-15T04:34:24.583+0000] {subprocess.py:106} INFO - #8 0xaaaabec73370 <unknown>
[2024-12-15T04:34:24.583+0000] {subprocess.py:106} INFO - #9 0xaaaabecb8400 <unknown>
[2024-12-15T04:34:24.584+0000] {subprocess.py:106} INFO - #10 0xaaaabec714a4 <unknown>
[2024-12-15T04:34:24.584+0000] {subprocess.py:106} INFO - #11 0xaaaabec720e0 <unknown>
[2024-12-15T04:34:24.584+0000] {subprocess.py:106} INFO - #12 0xaaaabeee5ac0 <unknown>
[2024-12-15T04:34:24.584+0000] {subprocess.py:106} INFO - #13 0xaaaabeee8a64 <unknown>
[2024-12-15T04:34:24.585+0000] {subprocess.py:106} INFO - #14 0xaaaabeee8630 <unknown>
[2024-12-15T04:34:24.585+0000] {subprocess.py:106} INFO - #15 0xaaaabeed6d6c <unknown>
[2024-12-15T04:34:24.585+0000] {subprocess.py:106} INFO - #16 0xaaaabeee9128 <unknown>
[2024-12-15T04:34:24.585+0000] {subprocess.py:106} INFO - #17 0xaaaabeec1010 <unknown>
[2024-12-15T04:34:24.585+0000] {subprocess.py:106} INFO - #18 0xaaaabef08550 <unknown>
[2024-12-15T04:34:24.586+0000] {subprocess.py:106} INFO - #19 0xaaaabef08758 <unknown>
[2024-12-15T04:34:24.586+0000] {subprocess.py:106} INFO - #20 0xaaaabef17250 <unknown>
[2024-12-15T04:34:24.586+0000] {subprocess.py:106} INFO - #21 0xffffa5ecee58 <unknown>
[2024-12-15T04:34:24.586+0000] {subprocess.py:106} INFO - #22 0xffffa5f37f9c <unknown>
[2024-12-15T04:34:24.586+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.586+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.587+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.587+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.587+0000] {subprocess.py:106} INFO - #0 0xaaaabef17d44 <unknown>
[2024-12-15T04:34:24.587+0000] {subprocess.py:106} INFO - #1 0xaaaabec3e374 <unknown>
[2024-12-15T04:34:24.587+0000] {subprocess.py:106} INFO - #2 0xaaaabec4afe0 <unknown>
[2024-12-15T04:34:24.587+0000] {subprocess.py:106} INFO - #3 0xaaaabec43318 <unknown>
[2024-12-15T04:34:24.588+0000] {subprocess.py:106} INFO - #4 0xaaaabec427ac <unknown>
[2024-12-15T04:34:24.588+0000] {subprocess.py:106} INFO - #5 0xaaaabec444b8 <unknown>
[2024-12-15T04:34:24.588+0000] {subprocess.py:106} INFO - #6 0xaaaabec4457c <unknown>
[2024-12-15T04:34:24.588+0000] {subprocess.py:106} INFO - #7 0xaaaabec7b0c8 <unknown>
[2024-12-15T04:34:24.588+0000] {subprocess.py:106} INFO - #8 0xaaaabec73370 <unknown>
[2024-12-15T04:34:24.588+0000] {subprocess.py:106} INFO - #9 0xaaaabecb8400 <unknown>
[2024-12-15T04:34:24.589+0000] {subprocess.py:106} INFO - #10 0xaaaabec714a4 <unknown>
[2024-12-15T04:34:24.589+0000] {subprocess.py:106} INFO - #11 0xaaaabec720e0 <unknown>
[2024-12-15T04:34:24.589+0000] {subprocess.py:106} INFO - #12 0xaaaabeee5ac0 <unknown>
[2024-12-15T04:34:24.589+0000] {subprocess.py:106} INFO - #13 0xaaaabeee8a64 <unknown>
[2024-12-15T04:34:24.589+0000] {subprocess.py:106} INFO - #14 0xaaaabeee8630 <unknown>
[2024-12-15T04:34:24.589+0000] {subprocess.py:106} INFO - #15 0xaaaabeed6d6c <unknown>
[2024-12-15T04:34:24.590+0000] {subprocess.py:106} INFO - #16 0xaaaabeee9128 <unknown>
[2024-12-15T04:34:24.590+0000] {subprocess.py:106} INFO - #17 0xaaaabeec1010 <unknown>
[2024-12-15T04:34:24.590+0000] {subprocess.py:106} INFO - #18 0xaaaabef08550 <unknown>
[2024-12-15T04:34:24.590+0000] {subprocess.py:106} INFO - #19 0xaaaabef08758 <unknown>
[2024-12-15T04:34:24.590+0000] {subprocess.py:106} INFO - #20 0xaaaabef17250 <unknown>
[2024-12-15T04:34:24.590+0000] {subprocess.py:106} INFO - #21 0xffffa5ecee58 <unknown>
[2024-12-15T04:34:24.590+0000] {subprocess.py:106} INFO - #22 0xffffa5f37f9c <unknown>
[2024-12-15T04:34:24.591+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.591+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.591+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.591+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.591+0000] {subprocess.py:106} INFO - #0 0xaaaabef17d44 <unknown>
[2024-12-15T04:34:24.591+0000] {subprocess.py:106} INFO - #1 0xaaaabec3e374 <unknown>
[2024-12-15T04:34:24.592+0000] {subprocess.py:106} INFO - #2 0xaaaabec4afe0 <unknown>
[2024-12-15T04:34:24.592+0000] {subprocess.py:106} INFO - #3 0xaaaabec43318 <unknown>
[2024-12-15T04:34:24.592+0000] {subprocess.py:106} INFO - #4 0xaaaabec427ac <unknown>
[2024-12-15T04:34:24.592+0000] {subprocess.py:106} INFO - #5 0xaaaabec444b8 <unknown>
[2024-12-15T04:34:24.592+0000] {subprocess.py:106} INFO - #6 0xaaaabec4457c <unknown>
[2024-12-15T04:34:24.592+0000] {subprocess.py:106} INFO - #7 0xaaaabec7b0c8 <unknown>
[2024-12-15T04:34:24.593+0000] {subprocess.py:106} INFO - #8 0xaaaabec73370 <unknown>
[2024-12-15T04:34:24.593+0000] {subprocess.py:106} INFO - #9 0xaaaabecb8400 <unknown>
[2024-12-15T04:34:24.593+0000] {subprocess.py:106} INFO - #10 0xaaaabec714a4 <unknown>
[2024-12-15T04:34:24.593+0000] {subprocess.py:106} INFO - #11 0xaaaabec720e0 <unknown>
[2024-12-15T04:34:24.593+0000] {subprocess.py:106} INFO - #12 0xaaaabeee5ac0 <unknown>
[2024-12-15T04:34:24.593+0000] {subprocess.py:106} INFO - #13 0xaaaabeee8a64 <unknown>
[2024-12-15T04:34:24.594+0000] {subprocess.py:106} INFO - #14 0xaaaabeee8630 <unknown>
[2024-12-15T04:34:24.594+0000] {subprocess.py:106} INFO - #15 0xaaaabeed6d6c <unknown>
[2024-12-15T04:34:24.594+0000] {subprocess.py:106} INFO - #16 0xaaaabeee9128 <unknown>
[2024-12-15T04:34:24.595+0000] {subprocess.py:106} INFO - #17 0xaaaabeec1010 <unknown>
[2024-12-15T04:34:24.595+0000] {subprocess.py:106} INFO - #18 0xaaaabef08550 <unknown>
[2024-12-15T04:34:24.595+0000] {subprocess.py:106} INFO - #19 0xaaaabef08758 <unknown>
[2024-12-15T04:34:24.596+0000] {subprocess.py:106} INFO - #20 0xaaaabef17250 <unknown>
[2024-12-15T04:34:24.596+0000] {subprocess.py:106} INFO - #21 0xffffa5ecee58 <unknown>
[2024-12-15T04:34:24.596+0000] {subprocess.py:106} INFO - #22 0xffffa5f37f9c <unknown>
[2024-12-15T04:34:24.596+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.596+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.596+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.596+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.597+0000] {subprocess.py:106} INFO - #0 0xaaaabef17d44 <unknown>
[2024-12-15T04:34:24.597+0000] {subprocess.py:106} INFO - #1 0xaaaabec3e374 <unknown>
[2024-12-15T04:34:24.597+0000] {subprocess.py:106} INFO - #2 0xaaaabec4afe0 <unknown>
[2024-12-15T04:34:24.597+0000] {subprocess.py:106} INFO - #3 0xaaaabec43318 <unknown>
[2024-12-15T04:34:24.597+0000] {subprocess.py:106} INFO - #4 0xaaaabec427ac <unknown>
[2024-12-15T04:34:24.597+0000] {subprocess.py:106} INFO - #5 0xaaaabec444b8 <unknown>
[2024-12-15T04:34:24.597+0000] {subprocess.py:106} INFO - #6 0xaaaabec4457c <unknown>
[2024-12-15T04:34:24.597+0000] {subprocess.py:106} INFO - #7 0xaaaabec7b0c8 <unknown>
[2024-12-15T04:34:24.598+0000] {subprocess.py:106} INFO - #8 0xaaaabec73370 <unknown>
[2024-12-15T04:34:24.598+0000] {subprocess.py:106} INFO - #9 0xaaaabecb8400 <unknown>
[2024-12-15T04:34:24.598+0000] {subprocess.py:106} INFO - #10 0xaaaabec714a4 <unknown>
[2024-12-15T04:34:24.598+0000] {subprocess.py:106} INFO - #11 0xaaaabec720e0 <unknown>
[2024-12-15T04:34:24.598+0000] {subprocess.py:106} INFO - #12 0xaaaabeee5ac0 <unknown>
[2024-12-15T04:34:24.598+0000] {subprocess.py:106} INFO - #13 0xaaaabeee8a64 <unknown>
[2024-12-15T04:34:24.598+0000] {subprocess.py:106} INFO - #14 0xaaaabeee8630 <unknown>
[2024-12-15T04:34:24.598+0000] {subprocess.py:106} INFO - #15 0xaaaabeed6d6c <unknown>
[2024-12-15T04:34:24.599+0000] {subprocess.py:106} INFO - #16 0xaaaabeee9128 <unknown>
[2024-12-15T04:34:24.599+0000] {subprocess.py:106} INFO - #17 0xaaaabeec1010 <unknown>
[2024-12-15T04:34:24.599+0000] {subprocess.py:106} INFO - #18 0xaaaabef08550 <unknown>
[2024-12-15T04:34:24.599+0000] {subprocess.py:106} INFO - #19 0xaaaabef08758 <unknown>
[2024-12-15T04:34:24.599+0000] {subprocess.py:106} INFO - #20 0xaaaabef17250 <unknown>
[2024-12-15T04:34:24.599+0000] {subprocess.py:106} INFO - #21 0xffffa5ecee58 <unknown>
[2024-12-15T04:34:24.599+0000] {subprocess.py:106} INFO - #22 0xffffa5f37f9c <unknown>
[2024-12-15T04:34:24.600+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.600+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.600+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.600+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.600+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.600+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.601+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.601+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.601+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.601+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.601+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.601+0000] {subprocess.py:106} INFO - #7 0xaaaac7e36db4 <unknown>
[2024-12-15T04:34:24.601+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.601+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.602+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.602+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.602+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.602+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.602+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.602+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.602+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.603+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.603+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.603+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.603+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.603+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.603+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.603+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.603+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.604+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.604+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.604+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.604+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.604+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.604+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.604+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.604+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.605+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.605+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.605+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.605+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.605+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.605+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.605+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.606+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.606+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.606+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.606+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.606+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.606+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.606+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.607+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.607+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.607+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.607+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.607+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.607+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.607+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.607+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.608+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.608+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.608+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.608+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.608+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.608+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.608+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.608+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.609+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.609+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.609+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.609+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.609+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.609+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.609+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.609+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.610+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.610+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.610+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.610+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.610+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.610+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.610+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.610+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.611+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.611+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.611+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.611+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.611+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.611+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.611+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.612+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.612+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.612+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.612+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.612+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.612+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.612+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.612+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.613+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.613+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.613+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.613+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.613+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.613+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.613+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.613+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.614+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.614+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.614+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.614+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.614+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.614+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.614+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.615+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.615+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.615+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.615+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.615+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.615+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.615+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.615+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.616+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.616+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.616+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.616+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.616+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.616+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.616+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.616+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.617+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.617+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.617+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.617+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.617+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.617+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.618+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.618+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.618+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.618+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.618+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.618+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.618+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.619+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.619+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.619+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.619+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.619+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.619+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.619+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.620+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.620+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.620+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.620+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.620+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.621+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.621+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.621+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.622+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.622+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.622+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.622+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.622+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.623+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.623+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.623+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.623+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.623+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.623+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.624+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.624+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.624+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.624+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.624+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.624+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.624+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.624+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.625+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.625+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.625+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.625+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.625+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.625+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.626+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.626+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.626+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.626+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.626+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.626+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.626+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.627+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.627+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.627+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.627+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.627+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.627+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.627+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.627+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.628+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.628+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.628+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.628+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.628+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.628+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.628+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.628+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.629+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.629+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.629+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.629+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.629+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.629+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.629+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.629+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.630+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.630+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.630+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.630+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.630+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.630+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.630+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.631+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.631+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.631+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.631+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.631+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.631+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.631+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.631+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.632+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.632+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.632+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.632+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.632+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.632+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.632+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.632+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.633+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.633+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.633+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.633+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.633+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.633+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.633+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.634+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.634+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.634+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.634+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.634+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.634+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.634+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.635+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.635+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.635+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.635+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.635+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.635+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.636+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.636+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.636+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.636+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.636+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.637+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.637+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.637+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.637+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.638+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.638+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.638+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.638+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.639+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.639+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.639+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.639+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.639+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.640+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.640+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.640+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.640+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.640+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.641+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.641+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.641+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.642+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.642+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.642+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.642+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.643+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.643+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.643+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.643+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.643+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.643+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.644+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.644+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.644+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.645+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.645+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.645+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.645+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.645+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.645+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.645+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.646+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.646+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.646+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.646+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.646+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.646+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.646+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.647+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.647+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.647+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.647+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.647+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.647+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.647+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.647+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.648+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.648+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.648+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.648+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.648+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.648+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.648+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.648+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.649+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.649+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.649+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.649+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.649+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.649+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.649+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.649+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.650+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.650+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.650+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.650+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.650+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.650+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.650+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.650+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.651+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.651+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.651+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.651+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.651+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.651+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.651+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.652+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.652+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.652+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T04:34:24.652+0000] {subprocess.py:106} INFO - 
[2024-12-15T04:34:24.652+0000] {subprocess.py:106} INFO - 데이터 추출 중 오류 발생: Message: stale element reference: stale element not found
[2024-12-15T04:34:24.652+0000] {subprocess.py:106} INFO -   (Session info: chrome=124.0.6367.78); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
[2024-12-15T04:34:24.652+0000] {subprocess.py:106} INFO - Stacktrace:
[2024-12-15T04:34:24.652+0000] {subprocess.py:106} INFO - #0 0xaaaac80d7d44 <unknown>
[2024-12-15T04:34:24.653+0000] {subprocess.py:106} INFO - #1 0xaaaac7dfe374 <unknown>
[2024-12-15T04:34:24.653+0000] {subprocess.py:106} INFO - #2 0xaaaac7e0afe0 <unknown>
[2024-12-15T04:34:24.653+0000] {subprocess.py:106} INFO - #3 0xaaaac7e03318 <unknown>
[2024-12-15T04:34:24.653+0000] {subprocess.py:106} INFO - #4 0xaaaac7e027ac <unknown>
[2024-12-15T04:34:24.653+0000] {subprocess.py:106} INFO - #5 0xaaaac7e044b8 <unknown>
[2024-12-15T04:34:24.653+0000] {subprocess.py:106} INFO - #6 0xaaaac7e0457c <unknown>
[2024-12-15T04:34:24.653+0000] {subprocess.py:106} INFO - #7 0xaaaac7e3b0c8 <unknown>
[2024-12-15T04:34:24.653+0000] {subprocess.py:106} INFO - #8 0xaaaac7e33370 <unknown>
[2024-12-15T04:34:24.654+0000] {subprocess.py:106} INFO - #9 0xaaaac7e78400 <unknown>
[2024-12-15T04:34:24.654+0000] {subprocess.py:106} INFO - #10 0xaaaac7e314a4 <unknown>
[2024-12-15T04:34:24.654+0000] {subprocess.py:106} INFO - #11 0xaaaac7e320e0 <unknown>
[2024-12-15T04:34:24.654+0000] {subprocess.py:106} INFO - #12 0xaaaac80a5ac0 <unknown>
[2024-12-15T04:34:24.654+0000] {subprocess.py:106} INFO - #13 0xaaaac80a8a64 <unknown>
[2024-12-15T04:34:24.654+0000] {subprocess.py:106} INFO - #14 0xaaaac80a8630 <unknown>
[2024-12-15T04:34:24.654+0000] {subprocess.py:106} INFO - #15 0xaaaac8096d6c <unknown>
[2024-12-15T04:34:24.654+0000] {subprocess.py:106} INFO - #16 0xaaaac80a9128 <unknown>
[2024-12-15T04:34:24.655+0000] {subprocess.py:106} INFO - #17 0xaaaac8081010 <unknown>
[2024-12-15T04:34:24.655+0000] {subprocess.py:106} INFO - #18 0xaaaac80c8550 <unknown>
[2024-12-15T04:34:24.655+0000] {subprocess.py:106} INFO - #19 0xaaaac80c8758 <unknown>
[2024-12-15T04:34:24.655+0000] {subprocess.py:106} INFO - #20 0xaaaac80d7250 <unknown>
[2024-12-15T04:34:24.655+0000] {subprocess.py:106} INFO - #21 0xffffac2cee58 <unknown>
[2024-12-15T04:34:24.655+0000] {subprocess.py:106} INFO - #22 0xffffac337f9c <unknown>
[2024-12-15T05:25:13.066+0000] {timeout.py:68} ERROR - Process timed out, PID: 1637
[2024-12-15T05:25:13.106+0000] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2024-12-15T05:25:13.185+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: Timeout, PID: 1637
[2024-12-15T05:25:13.237+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_etl, task_id=collect_data, run_id=scheduled__2024-12-14T04:00:00+00:00, execution_date=20241214T040000, start_date=20241215T042137, end_date=20241215T052513
[2024-12-15T05:25:13.308+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T05:25:13.358+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 2
[2024-12-15T05:25:13.364+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-12-15T05:25:13.424+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T05:25:13.426+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
